#55 Implement search in Grid and List modes
graasp/graasp-compose pull request #134
Opened 2021-07-05 17:45 UTC by dialexo

From #55 this PR implements client-side local search functionality for Grid and List display modes:

![Peek 2021-07-05 19-33](https://user-images.githubusercontent.com/14943421/124504876-95b81900-ddc8-11eb-8151-c082c8f85969.gif)

Also improves grid header display to be consistent with table view header:

Before | After
--- | ---
![Screenshot from 2021-07-05 19-36-29](https://user-images.githubusercontent.com/14943421/124505166-31498980-ddc9-11eb-860e-7630d2692856.png) |  ![Screenshot from 2021-07-05 19-35-03](https://user-images.githubusercontent.com/14943421/124505176-34dd1080-ddc9-11eb-9d98-5673acc13417.png)

### Summary

- implements `useItemSearch` hook, which manages search state and returns search results + `ItemSearchInput` component to render the text input
- forward this `ItemSearchInput` through `ItemsGrid` and `ItemsTable` to `TableToolbar`
- harmonizes table and grid headers to use `TableToolbar` in both cases, add padding to `EmptyItem`
- adds integration tests for search

2021-07-06 12:00 UTC, dialexo commented
Thanks a lot! Both issues have been fixed :+1:

2021-07-07 12:38 UTC, pyphilia requested changes
Nice! I really like how you factor out the search bar. I left some minor comments,

2021-07-07 12:38 UTC, pyphilia commented on src/components/main/TableToolbar.js
> +      {numSelected > 0 ? null : itemSearchInput}
Would the following work? `!numSelected  &&  itemSearchInput`
Perhaps you can even merge with the following condition.

2021-07-07 12:38 UTC, pyphilia commented on src/langs/fr.json
> +    "No search results found.": "Aucun résultat correspondant à la recherche."
`Aucun résultat ne correspond à la recherche`?

2021-07-07 14:13 UTC, dialexo commented
Thanks! I've pushed both changes

2021-07-07 14:40 UTC, pyphilia approved these changes

2021-07-07 14:50 UTC, merged