fix canEdit for category, add customized tag feature
graasp/graasp-compose pull request #253
Opened 2021-12-06 16:57 UTC by louisewang1

![image](https://user-images.githubusercontent.com/25419619/144888318-6e597092-c7de-4fd1-b381-2c2eb3daf5e8.png)

- fix the canEdit attribute for category selection, when user don't have editting right, the menu will be disabled
- add a input form to set customized tags for the item (in pic above)

2021-12-08 15:14 UTC, louisewang1 commented
close #252 
close #245 
close #247

2021-12-10 13:08 UTC, pyphilia requested changes
Thanks for this PR! 
I see your branch is still called 237/categories, I think it should be another branch refering to another issue? It's okay for this time, but keep in mind to create new branches for each new issue.
What do you think of `Tags` only instead of `Customized Tags`?

2021-12-10 13:08 UTC, pyphilia commented on src/components/item/sharing/CustomizedTags.js
> +          {t('Submit')}
I would actually use `save` instead, what do you think? (and change the icon or remove it accordingly)

2021-12-10 13:08 UTC, pyphilia commented on src/components/item/sharing/CustomizedTags.js
> +          id="customized-tags-input-box"
Unless this refers to an element, remove it.

2021-12-10 13:08 UTC, pyphilia commented on src/components/item/sharing/CustomizedTags.js
> +        {t('Eg. Tag1,Tag2,Tag3,...,TagN')}
Very engineer like ;) Maybe let's go for real example tags: `biology`, `moon`, ...

2021-12-12 20:18 UTC, louisewang1 commented
If I use "Tags", would this be confused with itemTags (like "published", "private")? Besides that I'm good with just "Tags".

2021-12-15 10:18 UTC, pyphilia requested changes
Nice PR! I left some comments 🐰

2021-12-15 10:18 UTC, pyphilia commented on src/components/item/sharing/CategorySelection.js
> +    .sort(compare);
I would rename the sorting function to something more explicit.

2021-12-15 10:18 UTC, pyphilia commented on src/components/item/sharing/CategorySelection.js
> +              placeholder={t('Please choose from list')}
`Please choose from the list`?

2021-12-15 10:18 UTC, pyphilia commented on src/components/item/sharing/CustomizedTagsEdit.js
> +        {t('Eg. English,Biology,Lab,Plants,...,Demo')}
Add spaces between values

2021-12-17 12:06 UTC, merged