295/improve share tab
graasp/graasp-compose pull request #298
Opened 2022-02-23 18:43 UTC by louisewang1

close #297 
close #295 

CC License Selection Layout:
![image](https://user-images.githubusercontent.com/25419619/155386202-0a6a50cb-6ca3-4abf-8778-375d1bf4d14b.png)

2022-02-28 14:47 UTC, louisewang1 commented on src/components/item/sharing/CCLicenseSelection.js
> +    maxWidth: SUBMIT_BUTTON_WIDTH,
Otherwise the button will be very fat (as wide as the texts above)

2022-03-03 16:26 UTC, louisewang1 commented
![Screenshot from 2022-03-03 17-14-54](https://user-images.githubusercontent.com/25419619/156607398-a31b60d0-b37b-4d50-9ae1-65d02813fcea.png)

2022-03-03 17:24 UTC, pyphilia requested changes

2022-03-03 17:24 UTC, pyphilia commented on src/components/item/sharing/CCLicenseSelection.js
> +    maxWidth: SUBMIT_BUTTON_WIDTH,
You might try `width:auto` apparently

2022-03-03 17:24 UTC, pyphilia commented on src/components/item/sharing/CCLicenseSelection.js
> +    redirect(url, { OpenInNewTab: true });
`openInNewTab`

2022-03-03 17:24 UTC, pyphilia commented on src/components/item/sharing/CCLicenseSelection.js
> +      </Dialog>
Maybe this can go in another component.
Also: irreversible exists in English right? It would be better than irrevertable^^

2022-03-04 13:22 UTC, pyphilia approved these changes
Cool, for me it's good to be merged. I've left a last minor comment 🌹

2022-03-04 13:22 UTC, pyphilia commented on src/components/item/sharing/CCLicenseSelection.js
> +    const url = 'https://creativecommons.org/about/cclicenses/';
Maybe let's factor this out in `constants`

2022-03-06 20:08 UTC, louisewang1 commented
Improve ShareTab, add CC License component

2022-03-06 20:08 UTC, merged