302/share tab layout
graasp/graasp-compose pull request #306
Opened 2022-03-16 20:26 UTC by louisewang1

close #302

2022-03-17 11:50 UTC, pyphilia requested changes

2022-03-17 11:50 UTC, pyphilia commented on src/components/item/sharing/VisibilitySelect.js
> +  const [open, setOpen] = useState(false);
`isPublishedSelected`?

2022-03-17 20:24 UTC, louisewang1 commented
I added the download button in this branch, so I requested a review again for the new feature I've implemented @pyphilia I decided to put the download Icon outside the sandwich menu, mainly because I made it an Icon Button, but in the menu, all buttons are text ones. Also in explorer, we use the Icon Button, so I try to unify them, and both can use the component from @graasp/ui. I also temporarily disabled a few tests related to publish item. I will work on the tests probably next week,

2022-03-29 16:29 UTC, pyphilia requested changes
Big changes! Keep in mind to split as much as possible the process logic and the UI logic.

2022-03-30 14:58 UTC, merged