feat: add co-editor settings
graasp/graasp-compose pull request #373
Opened 2022-06-06 15:10 UTC by louisewang1

Add co-editor display setting in publish tab

2022-06-06 15:15 UTC, louisewang1 commented
![image](https://user-images.githubusercontent.com/25419619/172190293-c314d74f-24bf-463d-bcfd-6a9b5f6e45ca.png)

2022-06-07 08:20 UTC, pyphilia requested changes
Thanks for the PR! I've left some comments :
Could we add trivial tests? Check the setting is displayed, and you can click it and it trigger the correct request.

2022-06-07 08:20 UTC, pyphilia commented on src/components/item/publish/CoEditorSettings.js
> +  const { itemId } = useParams();
You can get the item id from the item as well, for consistency.

2022-06-07 08:20 UTC, pyphilia commented on src/components/item/publish/CoEditorSettings.js
> +          'Do you want to display co-editors after published? All users with edit permission will be displayed.',
`Do you want to display co-editors on the publication page? All users with edit or admin permissions will be displayed.`

2022-06-07 08:20 UTC, pyphilia commented on src/components/item/publish/CoEditorSettings.js
> +          label={t(DISPLAY_CO_EDITOR_OPTIONS.NO.label)}
I think we can go with a `Object.values(DISPLAY_CO_EDITOR_OPTIONS).map(...)`

2022-06-07 08:20 UTC, pyphilia commented on src/config/constants.js
> +export const DISPLAY_CO_EDITOR_OPTIONS = {
`DISPLAY_CO_EDITORS_OPTIONS`

2022-06-22 14:28 UTC, louisewang1 commented
checkbox for email notification
![image](https://user-images.githubusercontent.com/25419619/175054338-bbcef01d-2d2b-452d-926c-232b818ae6cf.png)

2022-06-27 12:17 UTC, pyphilia requested changes
Thanks for the PR! I've left some minor comments 🍇

2022-07-04 16:45 UTC, merged