Migration to MUI5 (and TS)
graasp/graasp-compose pull request #462
Opened 2022-10-19 14:43 UTC by pyphilia

This PR is XXXXX-large so we maybe you want to divide it between you.. big changes because of mui5. 

close #455 
close #289

2022-10-20 13:13 UTC, juancarlosfarah requested changes
😅 

Looks good! Just a lot of minor comments. If you don't want to tackle them within this PR, you can just create the issues.

💪

2022-10-20 13:13 UTC, juancarlosfarah commented on src/components/item/sharing/CsvInputParser.tsx
> +  const { t: commonT } = useTranslation(namespaces.common);
Read other messages about translations. An idea:

```
  const { t: translateBuilder } = useBuilderTranslation();
  const { t: translateMessages } = useMessagesTranslation();
  const { t: translateCommon } = useCommonTranslation();
```

In any case, at least change to `messagesT` for consistency.

2022-10-20 13:13 UTC, juancarlosfarah commented on src/components/item/sharing/ItemMembershipSelect.tsx
> +  const { t: enumT } = useTranslation(namespaces.enums);
See other messages about translations.

2022-10-20 13:13 UTC, juancarlosfarah commented on src/components/item/sharing/ItemMembershipSelect.tsx
> +  const labelId = showLabel ? 'permission-label' : undefined;
Factor out `permission-label`?

2022-10-20 13:13 UTC, juancarlosfarah commented on src/components/item/settings/LinkSettings.tsx
> +        showLinkIframe: event.target.checked,
You sure `event.target` is always defined?

2022-10-20 13:13 UTC, juancarlosfarah commented on src/components/item/settings/LinkSettings.tsx
> +        showLinkButton: event.target.checked,
You sure `event.target` is always defined?

2022-10-21 09:38 UTC, pyphilia commented on tsconfig.json
> +    "strict": false,
I didn't apply TS everywhere. I think we should go through it step by step, I've done a good amount of the files but not all of these. Strict enables strong rules for ts.

2022-10-21 09:39 UTC, pyphilia commented on tsconfig.json
> +  "exclude": ["cypress", "*.test.ts", "*.test.js"]
I remove these files from the build.

2022-10-21 09:39 UTC, pyphilia commented on .eslintrc
> +    "react/require-default-props": "off"
Yes!

2022-10-21 09:40 UTC, pyphilia commented on .eslintrc
> +        "@typescript-eslint/explicit-module-boundary-types": ["error"]
That error was applied on JS files, so I've disabled it and enabled it only for TS files.

2022-10-21 09:41 UTC, pyphilia commented on .eslintrc
> +    "react/react-in-jsx-scope": "off",
Since React 17 we don't need to include React in every file. But this error was still showing. Probably we need to update a dependency.

2022-10-24 14:44 UTC, merged